In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/philazar/Desktop/march-madness/data/data-2022/model-dev/training/raw_feats_2022_03_07.csv')

In [3]:
df.head()

,Season,TeamID,tourn_seed,AP,KPK,MAS,MOR,NET,POM,RPI,...,close_win_perc,win_perc_l10,oppg,pythag_wins,ppg_oppg_ratio,n_yrs_at_school,coach_tot_yrs,prev_wins,coach_cum_wp,school_cum_wp
0,2003,1421,16,250.4,250.400000,265.0,277.0,250.400000,273.0,186.0,...,0.625000,0.5,78.448276,0.247168,0.907692,7,7,0.0,0.000000,0.000000
1,2003,1112,1,2.0,2.571429,3.0,4.0,2.571429,3.0,2.0,...,0.727273,0.9,70.250000,0.902098,1.213015,20,20,2.0,0.672727,0.688525
2,2003,1113,10,31.6,31.600000,40.0,22.0,31.600000,32.0,32.0,...,0.454545,0.6,69.172414,0.745981,1.098205,5,11,0.0,0.000000,0.600000
3,2003,1141,11,45.6,45.600000,36.0,50.0,45.600000,50.0,44.0,...,0.800000,0.9,73.241379,0.715142,1.083333,6,6,0.0,0.000000,0.000000
4,2003,1143,8,37.2,37.200000,30.0,43.0,37.200000,40.0,33.0,...,0.800000,0.6,69.758621,0.679953,1.067721,7,18,1.0,0.454545,0.500000

In [17]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

df.describe()

,Season,TeamID,tourn_seed,AP,KPK,MAS,MOR,NET,POM,RPI,SAG,USA,avg_rank_c,avg_rank_l31,avg_rank_l61,avg_rank_l91,rank_l31_delta,rank_l61_delta,rank_l91_delta,avg_rank_pre,avg_rank_exp,conf_champ,major_conf,year_trend,win_perc,ppg,fg_perc,fg3_perc,ft_perc,rb_pg,orb_pg,drb_pg,apg,ast_tov,tov_pg,stl_pg,second_chance,p_fgm_ast,blk_pg,blk_to_fouls,fouls_pg,tsp,close_win_perc,win_perc_l10,oppg,pythag_wins,ppg_oppg_ratio,n_yrs_at_school,coach_tot_yrs,prev_wins,coach_cum_wp,school_cum_wp
count,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000,1203.000000
mean,2011.643392,1294.453034,8.728180,54.093134,53.751912,52.368307,58.887781,54.683266,56.904406,50.250732,57.011638,54.038351,54.665503,60.032410,63.117378,67.920113,1.093685,1.211173,1.211173,75.208148,1.694336,0.458853,0.507066,1.631811,0.727349,73.840774,0.458406,0.360253,0.708400,35.984233,11.277944,24.706289,14.413125,1.151311,12.730496,6.874926,1.439983,0.555658,3.875325,0.249979,17.100698,0.560270,0.644754,0.725852,65.983719,0.764260,1.121503,7.387365,12.234414,0.651704,0.348436,0.400425
std,5.272761,106.057005,4.671943,55.538894,54.592315,53.103074,60.302026,55.401362,58.830363,49.565722,59.203925,55.560750,55.195829,62.558044,64.513436,66.831933,0.302340,0.561551,0.561551,69.481994,1.173766,0.498511,0.500158,1.668968,0.098884,5.180948,0.022320,0.026209,0.036515,2.773829,1.888509,1.863597,1.821568,0.205689,1.689101,1.350644,0.222282,0.052693,1.180818,0.154626,3.377379,0.024740,0.124922,0.158051,4.876988,0.117576,0.069200,5.997468,7.939764,1.217955,0.283705,0.248143
min,2003.000000,1101.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.125000,1.000000,0.293040,0.114046,0.114046,1.285714,0.106809,0.000000,0.000000,-4.605170,0.366667,58.812500,0.384921,0.264901,0.595561,21.500000,5.363636,15.357143,9.354839,0.527397,7.387097,3.451613,0.877647,0.378995,0.655172,0.034735,2.285714,0.460374,0.142857,0.200000,50.428571,0.217346,0.894573,1.000000,1.000000,0.000000,0.000000,0.000000
25%,2007.000000,1209.000000,5.000000,17.000000,17.547619,17.666667,17.000000,17.708333,17.000000,17.562500,17.000000,17.000000,17.775000,18.000000,18.392857,19.937500,0.915816,0.893533,0.893533,23.330357,1.032181,0.000000,0.000000,1.388791,0.656250,70.237903,0.443735,0.341524,0.683459,34.238859,10.030777,23.492424,13.163978,1.011429,11.562500,5.917143,1.291085,0.519299,3.030777,0.172936,16.258065,0.543071,0.562500,0.600000,62.797059,0.694683,1.074105,3.000000,6.000000,0.000000,0.000000,0.200000
50%,2012.000000,1294.000000,9.000000,35.000000,34.500000,34.000000,36.000000,35.333333,36.000000,35.000000,35.000000,34.800000,35.500000,36.142857,39.166667,43.000000,1.080925,1.133333,1.133333,48.833333,1.404878,0.000000,1.000000,2.198335,0.733333,73.640000,0.458242,0.360225,0.708145,36.030303,11.322581,24.692308,14.343750,1.136240,12.666667,6.812500,1.425474,0.555394,3.758621,0.218213,17.625000,0.559546,0.647059,0.700000,65.875000,0.783208,1.118168,6.000000,11.000000,0.000000,0.428571,0.484848
75%,2016.000000,1393.000000,13.000000,68.333333,68.000000,63.000000,79.000000,68.100000,72.000000,61.000000,73.000000,68.333333,68.333333,79.000000,83.000000,94.708333,1.211609,1.384996,1.384996,105.733333,1.935691,1.000000,1.000000,2.565718,0.793103,77.370833,0.473089,0.378995,0.733572,37.770430,12.515152,25.872984,15.603030,1.278465,13.790491,7.666667,1.582748,0.591047,4.610799,0.272897,18.859606,0.577463,0.730303,0.800000,69.191176,0.850943,1.163554,10.000000,18.000000,1.000000,0.589572,0.588235
max,2021.000000,1463.000000,16.000000,290.333333,287.000000,300.000000,310.000000,302.000000,318.000000,287.000000,308.000000,290.333333,290.333333,322.833333,331.166667,318.000000,3.846154,6.571429,6.571429,305.000000,12.296296,1.000000,1.000000,2.890927,1.000000,92.115385,0.550868,0.437596,0.825641,46.137931,16.843750,30.939394,21.484848,2.107438,19.466667,11.823529,2.483221,0.719895,9.333333,1.729167,24.125000,0.639677,1.000000,1.000000,81.645161,0.977479,1.388011,37.000000,37.000000,6.000000,0.857143,0.805556

In [23]:
df.loc[df['pythag_wins'] > .97]

,Season,TeamID,tourn_seed,AP,KPK,MAS,MOR,NET,POM,RPI,SAG,USA,avg_rank_c,avg_rank_l31,avg_rank_l61,avg_rank_l91,rank_l31_delta,rank_l61_delta,rank_l91_delta,avg_rank_pre,avg_rank_exp,conf_champ,major_conf,year_trend,win_perc,ppg,fg_perc,fg3_perc,ft_perc,rb_pg,orb_pg,drb_pg,apg,ast_tov,tov_pg,stl_pg,second_chance,p_fgm_ast,blk_pg,blk_to_fouls,fouls_pg,tsp,close_win_perc,win_perc_l10,oppg,pythag_wins,ppg_oppg_ratio,n_yrs_at_school,coach_tot_yrs,prev_wins,coach_cum_wp,school_cum_wp
415,2015,1246,1,1.0,1.0,1.0,2.0,1.125,1.0,1.00,1.0,1.0,1.125,1.125,1.125,1.142857,1.000000,1.000000,1.000000,4.125,3.666667,1.0,1.0,2.485740,1.000000,74.911765,0.468684,0.349716,0.722424,38.176471,12.911765,25.264706,14.705882,1.385042,10.617647,6.558824,1.833795,0.566251,6.882353,0.404145,17.029412,0.566756,1.000,1.0,53.970588,0.977479,1.388011,6,23,5.0,0.755102,0.760870
484,2017,1211,1,2.0,2.0,1.0,3.0,2.500,1.0,8.00,1.0,2.0,2.500,2.375,4.750,8.250000,0.950000,1.900000,1.900000,18.375,7.350000,1.0,0.0,2.639771,0.969697,84.575758,0.517829,0.381933,0.737838,40.303030,9.363636,30.939394,16.030303,1.418231,11.303030,7.151515,1.461126,0.527944,4.454545,0.270718,16.454545,0.617314,0.875,0.9,61.151515,0.976555,1.383053,18,18,2.0,0.571429,0.558140
554,2019,1211,1,4.0,3.0,9.0,2.0,2.000,2.0,3.75,5.0,3.0,3.750,1.750,3.625,4.750000,0.466667,0.966667,0.966667,5.750,1.533333,0.0,0.0,2.773214,0.909091,88.848485,0.531798,0.365057,0.767409,38.636364,9.545455,29.090909,18.212121,1.757310,10.363636,7.545455,1.649123,0.565913,5.484848,0.341509,16.060606,0.633831,0.750,0.9,65.060606,0.972974,1.365626,20,20,2.0,0.607843,0.596154

In [19]:
teams_df = pd.read_csv('/Users/philazar/Desktop/march-madness/data/data-2022/MDataFiles_Stage1/MTeams.csv')

In [24]:
teams_df.loc[teams_df['TeamID'].isin([1246,1211,1211])]

     TeamID  TeamName  FirstD1Season  LastD1Season
110    1211   Gonzaga           1985          2022
145    1246  Kentucky           1985          2022

In [22]:
df.groupby('Season')['TeamID'].nunique()

Season
2003    65
2004    65
2005    65
2006    65
2007    65
2008    65
2009    65
2010    65
2011    68
2012    68
2013    68
2014    68
2015    68
2016    68
2017    68
2018    68
2019    68
2021    67
Name: TeamID, dtype: int64

In [25]:
len(df.columns)

52